### ISSUE TITLE
跳过了不少任务点

### ISSUE THREAD

**Issue by Hentai02** [yuban10703/autopass-chaoxing-video#1]
![QQ图片20210905132703.jpg](https://i.loli.net/2021/09/05/Ku3i9w4ZoahLXW8.jpg)
![QQ图片20210905132646.jpg](https://i.loli.net/2021/09/05/CKilfFm17a4XBEM.jpg)

**Comment by yuban10703** [comment]
顺序的乱的

**Comment by yuban10703** [comment]
解决了

**Comment by Hentai02** [comment]
大佬啥时候把其他任务点安排上

**Comment by yuban10703** [comment]
其他的任务点用不了多少时间吧,没必要吧...

**Comment by Hentai02** [comment]
![Screenshot_2021-09-05-19-46-50-096_com termux](https://user-images.githubusercontent.com/54672936/132126085-63217860-945c-452c-bdb8-5ed3d9d976b3.jpg)
报错

**Comment by yuban10703** [comment]
阿哲

**Comment by yuban10703** [comment]
要不加个QQ? 把号给我试试?......

**Comment by Hentai02** [comment]
488165279
